#!/bin/bash
set -eu -o pipefail

prev_ifs=$IFS
IFS=$'\n'
desktop_dirs=(${XDG_DATA_HOME-~/.local/share}/applications /usr/share/applications)
desktop_paths=(`find "${desktop_dirs[@]}" -type f -name "*.desktop" ! -name "chrome-*-*.desktop" 2>/dev/null || :`)
desktop_names=("${desktop_paths[@]##*/}")
desktop_names=("${desktop_names[@]%.desktop}")
IFS=$prev_ifs

result=`IFS=$'\n'; echo "${desktop_names[*]}" | sort -u | pmenu -n run "$@"`

for i in ${!desktop_names[@]}; do
  [[ ${desktop_names[$i]} == $result ]] || continue

  desktop_path=${desktop_paths[$i]}
  break
done
[[ -n ${desktop_path-} ]] || exec $result

desktop_exec=`grep -oP -m 1 "(?<=^Exec=).+" "$desktop_path"`
desktop_exec=${desktop_exec// -[[:alnum:]]* %[[:alpha:]]/}
desktop_exec=${desktop_exec// %[[:alpha:]]/}
if grep -q ^Terminal=true "$desktop_path"; then
  exec $desktop_exec
else
  exec setsid $desktop_exec
fi
